const staticDefaultMovies = [
    {
        "Title": "The Shawshank Redemption",
        "Year": "1994",
        "Rated": "R",
        "Director": "Frank Darabont",
        "Genre": "Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "9.3",
        "imdbID": "tt0111161",
        "Type": "movie"
    },
    {
        "Title": "The Godfather",
        "Year": "1972",
        "Rated": "R",
        "Director": "Francis Ford Coppola",
        "Genre": "Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_QL75_UY562_CR8,0,380,562_.jpg",
        "imdbRating": "9.2",
        "imdbID": "tt0068646",
        "Type": "movie"
    },
    {
        "Title": "The Dark Knight",
        "Year": "2008",
        "Rated": "PG-13",
        "Director": "Christopher Nolan",
        "Genre": "Action, Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "9.1",
        "imdbID": "tt0468569",
        "Type": "movie"
    },
    {
        "Title": "The Godfather Part II",
        "Year": "1974",
        "Rated": "R",
        "Director": "Francis Ford Coppola",
        "Genre": "Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "9.0",
        "imdbID": "tt0071562",
        "Type": "movie"
    },
    {
        "Title": "12 Angry Men",
        "Year": "1957",
        "Rated": "Approved",
        "Director": "Sidney Lumet",
        "Genre": "Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_QL75_UX380_CR0,11,380,562_.jpg",
        "imdbRating": "9.0",
        "imdbID": "tt0050083",
        "Type": "movie"
    },
    {
        "Title": "Schindler's List",
        "Year": "1994",
        "Rated": "R",
        "Director": "Steven Spielberg",
        "Genre": "Biography, Drama, History",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "9.0",
        "imdbID": "tt0108052",
        "Type": "movie"
    },
    {
        "Title": "The Lord of the Rings: The Return of the King",
        "Year": "2003",
        "Rated": "PG-13",
        "Director": "Peter Jackson",
        "Genre": "Adventure, Drama, Fantasy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "9.0",
        "imdbID": "tt0167260",
        "Type": "movie"
    },
    {
        "Title": "Pulp Fiction",
        "Year": "1994",
        "Rated": "R",
        "Director": "Quentin Tarantino",
        "Genre": "Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_QL75_UY562_CR3,0,380,562_.jpg",
        "imdbRating": "8.8",
        "imdbID": "tt0110912",
        "Type": "movie"
    },
    {
        "Title": "The Lord of the Rings: The Fellowship of the Ring",
        "Year": "2001",
        "Rated": "PG-13",
        "Director": "Peter Jackson",
        "Genre": "Adventure, Drama, Fantasy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg",
        "imdbRating": "8.9",
        "imdbID": "tt0120737",
        "Type": "movie"
    },
    {
        "Title": "The Good, the Bad and the Ugly",
        "Year": "1967",
        "Rated": "R",
        "Director": "Sergio Leone",
        "Genre": "Adventure, Drama, Western",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "8.8",
        "imdbID": "tt0060196",
        "Type": "movie"
    },
    {
        "Title": "Forrest Gump",
        "Year": "1994",
        "Rated": "PG-13",
        "Director": "Robert Zemeckis",
        "Genre": "Drama, Romance",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_QL75_UY562_CR4,0,380,562_.jpg",
        "imdbRating": "8.8",
        "imdbID": "tt0109830",
        "Type": "movie"
    },
    {
        "Title": "Fight Club",
        "Year": "1999",
        "Rated": "R",
        "Director": "David Fincher",
        "Genre": "Crime, Drama, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "8.8",
        "imdbID": "tt0137523",
        "Type": "movie"
    },
    {
        "Title": "Inception",
        "Year": "2010",
        "Rated": "PG-13",
        "Director": "Christopher Nolan",
        "Genre": "Action, Adventure, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.8",
        "imdbID": "tt1375666",
        "Type": "movie"
    },
    {
        "Title": "Saving Private Ryan",
        "Year": "1998",
        "Rated": "R",
        "Director": "Steven Spielberg",
        "Genre": "Drama, War",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0120815",
        "Type": "movie"
    },
    {
        "Title": "Star Wars: Episode V - The Empire Strikes Back",
        "Year": "1980",
        "Rated": "PG",
        "Director": "Irvin Kershner",
        "Genre": "Action, Adventure, Fantasy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTkxNGFlNDktZmJkNC00MDdhLTg0MTEtZjZiYWI3MGE5NWIwXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.7",
        "imdbID": "tt0080684",
        "Type": "movie"
    },
    {
        "Title": "The Matrix",
        "Year": "1999",
        "Rated": "R",
        "Director": "Lana Wachowski, Lilly Wachowski",
        "Genre": "Action, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "8.7",
        "imdbID": "tt0133093",
        "Type": "movie"
    },
    {
        "Title": "GoodFellas",
        "Year": "1990",
        "Rated": "R",
        "Director": "Martin Scorsese",
        "Genre": "Biography, Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_QL75_UX380_CR0,3,380,562_.jpg",
        "imdbRating": "8.7",
        "imdbID": "tt0099685",
        "Type": "movie"
    },
    {
        "Title": "One Flew Over the Cuckoo's Nest",
        "Year": "1975",
        "Rated": "R",
        "Director": "Miloš Forman",
        "Genre": "Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYjBkMjgzMzYtNzRiMS00NDc3LWE4YTUtZjYxYjZhNjNhYzhhXkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0073486",
        "Type": "movie"
    },
    {
        "Title": "Seven",
        "Year": "1995",
        "Rated": "R",
        "Director": "David Fincher",
        "Genre": "Crime, Drama, Mystery",
        "Poster": "https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjODdhMDU5NDM1XkEyXkFqcGc@._V1_QL75_UX380_CR0,16,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0114369",
        "Type": "movie"
    },
    {
        "Title": "Seven Samurai",
        "Year": "1954",
        "Rated": "Not Rated",
        "Director": "Akira Kurosawa",
        "Genre": "Action, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZjliMWExOTMtZDQ3ZS00NWU3LWIyN2EtMjllNzk3ZTNlYzg4XkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0047478",
        "Type": "movie"
    },
    {
        "Title": "It's a Wonderful Life",
        "Year": "1946",
        "Rated": "PG",
        "Director": "Frank Capra",
        "Genre": "Drama, Family, Fantasy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMDM4OWFhYjEtNTE5Yy00NjcyLTg5N2UtZDQwNDZlYjlmNDU5XkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0038650",
        "Type": "movie"
    },
    {
        "Title": "The Silence of the Lambs",
        "Year": "1991",
        "Rated": "R",
        "Director": "Jonathan Demme",
        "Genre": "Crime, Drama, Horror",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0102926",
        "Type": "movie"
    },
    {
        "Title": "City of God",
        "Year": "2004",
        "Rated": "R",
        "Director": "Kátia Lund, Fernando Meirelles",
        "Genre": "Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0317248",
        "Type": "movie"
    },
    {
        "Title": "Life Is Beautiful",
        "Year": "1997",
        "Rated": "PG-13",
        "Director": "Roberto Benigni",
        "Genre": "Comedy, Drama, Romance",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZTBhOGYzZjQtYzE0Mi00MGIwLWE0MWYtNzMxNTM2OTFkM2NjXkEyXkFqcGc@._V1_QL75_UX380_CR0,2,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0118799",
        "Type": "movie"
    },
    {
        "Title": "Interstellar",
        "Year": "2014",
        "Rated": "PG-13",
        "Director": "Christopher Nolan",
        "Genre": "Adventure, Drama, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.7",
        "imdbID": "tt0816692",
        "Type": "movie"
    },
    {
        "Title": "Spirited Away",
        "Year": "2003",
        "Rated": "PG",
        "Director": "Hayao Miyazaki",
        "Genre": "Animation, Adventure, Family",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0245429",
        "Type": "movie"
    },
    {
        "Title": "Star Wars: Episode IV - A New Hope",
        "Year": "1977",
        "Rated": "PG",
        "Director": "George Lucas",
        "Genre": "Action, Adventure, Fantasy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BOGUwMDk0Y2MtNjBlNi00NmRiLTk2MWYtMGMyMDlhYmI4ZDBjXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0076759",
        "Type": "movie"
    },
    {
        "Title": "Terminator 2: Judgment Day",
        "Year": "1991",
        "Rated": "R",
        "Director": "James Cameron",
        "Genre": "Action, Adventure, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNGMyMGNkMDUtMjc2Ni00NWFlLTgyODEtZTY2MzBiZTg0OWZiXkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0103064",
        "Type": "movie"
    },
    {
        "Title": "The Green Mile",
        "Year": "1999",
        "Rated": "R",
        "Director": "Frank Darabont",
        "Genre": "Crime, Drama, Fantasy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0120689",
        "Type": "movie"
    },
    {
        "Title": "Back to the Future",
        "Year": "1985",
        "Rated": "PG",
        "Director": "Robert Zemeckis",
        "Genre": "Adventure, Comedy, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZmM3ZjE0NzctNjBiOC00MDZmLTgzMTUtNGVlOWFlOTNiZDJiXkEyXkFqcGc@._V1_QL75_UX380_CR0,14,380,562_.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt0088763",
        "Type": "movie"
    },
    {
        "Title": "Parasite",
        "Year": "2019",
        "Rated": "R",
        "Director": "Bong Joon Ho",
        "Genre": "Drama, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt6751668",
        "Type": "movie"
    },
    {
        "Title": "Léon: The Professional",
        "Year": "1994",
        "Rated": "R",
        "Director": "Luc Besson",
        "Genre": "Action, Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNGRkYTNhOWQtYmI0Ni00MjZhLWJmMzAtMTA2Mjg4NGNiNDU0XkEyXkFqcGc@._V1_QL75_UX380_CR0,2,380,562_.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt0110413",
        "Type": "movie"
    },
    {
        "Title": "The Lion King",
        "Year": "1994",
        "Rated": "G",
        "Director": "Roger Allers, Rob Minkoff",
        "Genre": "Animation, Adventure, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZGRiZDZhZjItM2M3ZC00Y2IyLTk3Y2MtMWY5YjliNDFkZTJlXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt0110357",
        "Type": "movie"
    },
    {
        "Title": "The Pianist",
        "Year": "2003",
        "Rated": "R",
        "Director": "Roman Polanski",
        "Genre": "Biography, Drama, Music",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjEwNmEwYjgtNTk3ZC00NjljLTg5ZDctZTY3ZGQwZjRkZmQxXkEyXkFqcGc@._V1_QL75_UY562_CR14,0,380,562_.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt0253474",
        "Type": "movie"
    },
    {
        "Title": "The Departed",
        "Year": "2006",
        "Rated": "R",
        "Director": "Martin Scorsese",
        "Genre": "Crime, Drama, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_QL75_UY562_CR0,0,380,562_.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt0407887",
        "Type": "movie"
    },
    {
        "Title": "Whiplash",
        "Year": "2014",
        "Rated": "R",
        "Director": "Damien Chazelle",
        "Genre": "Drama, Music",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMDFjOWFkYzktYzhhMC00NmYyLTkwY2EtYjViMDhmNzg0OGFkXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt2582802",
        "Type": "movie"
    },
    {
        "Title": "The Prestige",
        "Year": "2006",
        "Rated": "PG-13",
        "Director": "Christopher Nolan",
        "Genre": "Drama, Mystery, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTM3MzQ5MjQ5OF5BMl5BanBnXkFtZTcwMTQ3NzMzMw@@._V1_QL75_UY562_CR0,0,380,562_.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt0482571",
        "Type": "movie"
    },
    {
        "Title": "The Usual Suspects",
        "Year": "1995",
        "Rated": "R",
        "Director": "Bryan Singer",
        "Genre": "Crime, Drama, Mystery",
        "Poster": "https://m.media-amazon.com/images/M/MV5BOTE5MDUxZDUtZWZmZC00NDVmLWFhOGQtNWI2YTc4NzY3MGQ0XkEyXkFqcGc@._V1_QL75_UX380_CR0,2,380,562_.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt0114814",
        "Type": "movie"
    },
    {
        "Title": "Grave of the Fireflies",
        "Year": "1989",
        "Rated": "Not Rated",
        "Director": "Isao Takahata",
        "Genre": "Animation, Drama, War",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNTY5MmE2OGMtN2IxNC00MDY4LTkwMGEtZDUzOTYyNWE0ZTNjXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt0095327",
        "Type": "movie"
    },
    {
        "Title": "Harakiri",
        "Year": "1964",
        "Rated": "Not Rated",
        "Director": "Masaki Kobayashi",
        "Genre": "Drama, Mystery",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZThiZjU5ZDQtZDI4Mi00ZGYyLTkzOTktYmIzZTFlZTkxYzg5XkEyXkFqcGc@._V1_QL75_UY562_CR5,0,380,562_.jpg",
        "imdbRating": "8.6",
        "imdbID": "tt0056058",
        "Type": "movie"
    },
    {
        "Title": "Django Unchained",
        "Year": "2012",
        "Rated": "R",
        "Director": "Quentin Tarantino",
        "Genre": "Drama, Western",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.5",
        "imdbID": "tt1853728",
        "Type": "movie"
    },
    {
        "Title": "WALL·E",
        "Year": "2008",
        "Rated": "G",
        "Director": "Andrew Stanton",
        "Genre": "Animation, Adventure, Family",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt0910970",
        "Type": "movie"
    },
    {
        "Title": "The Shining",
        "Year": "1980",
        "Rated": "R",
        "Director": "Stanley Kubrick",
        "Genre": "Drama, Horror",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt0081505",
        "Type": "movie"
    },
    {
        "Title": "Spider-Man: Into the Spider-Verse",
        "Year": "2018",
        "Rated": "PG",
        "Director": "Bob Persichetti, Peter Ramsey, Rodney Rothman",
        "Genre": "Animation, Action, Adventure",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt4633694",
        "Type": "movie"
    },
    {
        "Title": "Joker",
        "Year": "2019",
        "Rated": "R",
        "Director": "Todd Phillips",
        "Genre": "Crime, Drama, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNzY3OWQ5NDktNWQ2OC00ZjdlLThkMmItMDhhNDk3NTFiZGU4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt7286456",
        "Type": "movie"
    },
    {
        "Title": "Avengers: Endgame",
        "Year": "2019",
        "Rated": "PG-13",
        "Director": "Anthony Russo, Joe Russo",
        "Genre": "Action, Adventure, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt4154796",
        "Type": "movie"
    },
    {
        "Title": "Princess Mononoke",
        "Year": "1997",
        "Rated": "PG-13",
        "Director": "Hayao Miyazaki",
        "Genre": "Animation, Adventure, Fantasy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNjAzODViNGEtMjBkYi00N2U5LWJjNjAtY2U0MGJhZTEwOTU0XkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt0119698",
        "Type": "movie"
    },
    {
        "Title": "Oldboy",
        "Year": "2003",
        "Rated": "R",
        "Director": "Park Chan-wook",
        "Genre": "Action, Drama, Mystery",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTAwNzNjYWItZmI0Ni00ZTcyLWIwNWMtZjlmNGMxZTEyYTJmXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt0364569",
        "Type": "movie"
    },
    {
        "Title": "Once Upon a Time in America",
        "Year": "1984",
        "Rated": "R",
        "Director": "Sergio Leone",
        "Genre": "Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMDQ0ZTg2OGUtZjMyOC00M2M5LThkMmItZmM2MmUzMmIxMWJhXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt0087843",
        "Type": "movie"
    },
    {
        "Title": "The Dark Knight Rises",
        "Year": "2012",
        "Rated": "PG-13",
        "Director": "Christopher Nolan",
        "Genre": "Action, Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt1345836",
        "Type": "movie"
    },
    {
        "Title": "Aliens",
        "Year": "1986",
        "Rated": "R",
        "Director": "James Cameron",
        "Genre": "Action, Adventure, Horror",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZjIyNGJhYzYtN2I1My00OTVhLWEyMzItZTVjNDMzOTVkYWViXkEyXkFqcGc@._V1_QL75_UX380_CR0,6,380,562_.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt0090605",
        "Type": "movie"
    },
    {
        "Title": "Coco",
        "Year": "2017",
        "Rated": "PG",
        "Director": "Adrian Molina, Lee Unkrich",
        "Genre": "Animation, Adventure, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMDIyM2E2NTAtMzlhNy00ZGUxLWI1NjgtZDY5MzhiMDc5NGU3XkEyXkFqcGc@._V1_QL75_UY562_CR7,0,380,562_.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt2380307",
        "Type": "movie"
    },
    {
        "Title": "Avengers: Infinity War",
        "Year": "2018",
        "Rated": "PG-13",
        "Director": "Anthony Russo, Joe Russo",
        "Genre": "Action, Adventure, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt4154756",
        "Type": "movie"
    },
    {
        "Title": "Amadeus",
        "Year": "1984",
        "Rated": "PG",
        "Director": "Milos Forman",
        "Genre": "Biography, Drama, Music",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMzc2MjM0NTMtOGY4NC00NzY1LWE2ODUtZjMzY2RhNGNkZDAyXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt0086879",
        "Type": "movie"
    },
    {
        "Title": "Braveheart",
        "Year": "1995",
        "Rated": "R",
        "Director": "Mel Gibson",
        "Genre": "Biography, Drama, War",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNGMxZDBhNGQtYTZlNi00N2UzLWI4NDEtNmUzNWM2NTdmZDA0XkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt0112573",
        "Type": "movie"
    },
    {
        "Title": "Toy Story",
        "Year": "1995",
        "Rated": "G",
        "Director": "John Lasseter",
        "Genre": "Animation, Adventure, Comedy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt0114709",
        "Type": "movie"
    },
    {
        "Title": "Inglourious Basterds",
        "Year": "2009",
        "Rated": "R",
        "Director": "Quentin Tarantino",
        "Genre": "Adventure, Drama, War",
        "Poster": "https://m.media-amazon.com/images/M/MV5BODZhMWJlNjYtNDExNC00MTIzLTllM2ItOGQ2NGVjNDQ3MzkzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt0361748",
        "Type": "movie"
    },
    {
        "Title": "Good Will Hunting",
        "Year": "1998",
        "Rated": "R",
        "Director": "Gus Van Sant",
        "Genre": "Drama, Romance",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNDdjZGQ5YzEtNTc2My00Mjc0LWFlMTctYzkwMzZlNzdiZWYzXkEyXkFqcGc@._V1_QL75_UX380_CR0,9,380,562_.jpg",
        "imdbRating": "8.4",
        "imdbID": "tt0119217",
        "Type": "movie"
    },
    {
        "Title": "Requiem for a Dream",
        "Year": "2000",
        "Rated": "NC-17",
        "Director": "Darren Aronofsky",
        "Genre": "Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BN2ZlMjIzZjctYzA2My00ZWYyLWI4ZjctMGI2NWYyNzFiZjAwXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt0180093",
        "Type": "movie"
    },
    {
        "Title": "2001: A Space Odyssey",
        "Year": "1968",
        "Rated": "G",
        "Director": "Stanley Kubrick",
        "Genre": "Adventure, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNjU0NDFkMTQtZWY5OS00MmZhLTg3Y2QtZmJhMzMzMWYyYjc2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt0062622",
        "Type": "movie"
    },
    {
        "Title": "Eternal Sunshine of the Spotless Mind",
        "Year": "2004",
        "Rated": "R",
        "Director": "Michel Gondry",
        "Genre": "Drama, Romance, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt0338013",
        "Type": "movie"
    },
    {
        "Title": "The Hunt",
        "Year": "2012",
        "Rated": "R",
        "Director": "Thomas Vinterberg",
        "Genre": "Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTg2NDg3ODg4NF5BMl5BanBnXkFtZTcwNzk3NTc3Nw@@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt2106476",
        "Type": "movie"
    },
    {
        "Title": "Reservoir Dogs",
        "Year": "1992",
        "Rated": "R",
        "Director": "Quentin Tarantino",
        "Genre": "Crime, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMmMzYjg4NDctYWY0Mi00OGViLWIzMTMtYWNlZGY5ZDJmYjk3XkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt0105236",
        "Type": "movie"
    },
    {
        "Title": "Up",
        "Year": "2009",
        "Rated": "PG",
        "Director": "Pete Docter, Bob Peterson",
        "Genre": "Animation, Adventure, Comedy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNmI1ZTc5MWMtMDYyOS00ZDc2LTkzOTAtNjQ4NWIxNjYyNDgzXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.3",
        "imdbID": "tt1049413",
        "Type": "movie"
    },
    {
        "Title": "Oppenheimer",
        "Year": "2023",
        "Rated": "R",
        "Director": "Christopher Nolan",
        "Genre": "Biography, Drama, History",
        "Poster": "https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTJmNTM5MjVmYTQ4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt15398776",
        "Type": "movie"
    },
    {
        "Title": "Spider-Man: No Way Home",
        "Year": "2021",
        "Rated": "PG-13",
        "Director": "Jon Watts",
        "Genre": "Action, Adventure, Fantasy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMmFiZGZjMmEtMTA0Ni00MzA2LTljMTYtZGI2MGJmZWYzZTQ2XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt10872600",
        "Type": "movie"
    },
    {
        "Title": "A Beautiful Mind",
        "Year": "2001",
        "Rated": "PG-13",
        "Director": "Ron Howard",
        "Genre": "Biography, Drama",
        "Poster": "https://upload.wikimedia.org/wikipedia/en/b/b8/A_Beautiful_Mind_Poster.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt0253124",
        "Type": "movie"
    },
    {
        "Title": "Catch Me If You Can",
        "Year": "2002",
        "Rated": "PG-13",
        "Director": "Steven Spielberg",
        "Genre": "Biography, Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt0264464",
        "Type": "movie"
    },
    {
        "Title": "V for Vendetta",
        "Year": "2006",
        "Rated": "R",
        "Director": "James McTeigue",
        "Genre": "Action, Drama, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt0434409",
        "Type": "movie"
    },
    {
        "Title": "Shutter Island",
        "Year": "2010",
        "Rated": "R",
        "Director": "Martin Scorsese",
        "Genre": "Drama, Mystery, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BN2FjNWExYzEtY2YzOC00YjNlLTllMTQtNmIwM2Q1YzBhOWM1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt1130884",
        "Type": "movie"
    },
    {
        "Title": "The Wolf of Wall Street",
        "Year": "2013",
        "Rated": "R",
        "Director": "Martin Scorsese",
        "Genre": "Biography, Comedy, Crime",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt0993846",
        "Type": "movie"
    },
    {
        "Title": "Blade Runner",
        "Year": "1982",
        "Rated": "R",
        "Director": "Ridley Scott",
        "Genre": "Action, Drama, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BOWQ4YTBmNTQtMDYxMC00NGFjLTkwOGQtNzdhNmY1Nzc1MzUxXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt0083658",
        "Type": "movie"
    },
    {
        "Title": "The Truman Show",
        "Year": "1998",
        "Rated": "PG",
        "Director": "Peter Weir",
        "Genre": "Comedy, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNzA3ZjZlNzYtMTdjMy00NjMzLTk5ZGYtMTkyYzNiOGM1YmM3XkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt0120382",
        "Type": "movie"
    },
    {
        "Title": "Deadpool",
        "Year": "2016",
        "Rated": "R",
        "Director": "Tim Miller",
        "Genre": "Action, Comedy, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNzY3ZWU5NGQtOTViNC00ZWVmLTliNjAtNzViNzlkZWQ4YzQ4XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "8.0",
        "imdbID": "tt1431045",
        "Type": "movie"
    },
    {
        "Title": "Mad Max: Fury Road",
        "Year": "2015",
        "Rated": "R",
        "Director": "George Miller",
        "Genre": "Action, Adventure, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZDRkODJhOTgtOTc1OC00NTgzLTk4NjItNDgxZDY4YjlmNDY2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt1392190",
        "Type": "movie"
    },
    {
        "Title": "Guardians of the Galaxy",
        "Year": "2014",
        "Rated": "PG-13",
        "Director": "James Gunn",
        "Genre": "Action, Adventure, Comedy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BM2ZmNjQ2MzAtNDlhNi00MmQyLWJhZDMtNmJiMjFlOWY4MzcxXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.0",
        "imdbID": "tt2015381",
        "Type": "movie"
    },
    {
        "Title": "Logan",
        "Year": "2017",
        "Rated": "R",
        "Director": "James Mangold",
        "Genre": "Action, Drama, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt3315342",
        "Type": "movie"
    },
    {
        "Title": "The Many Saints of Newark",
        "Year": "2021",
        "Rated": "R",
        "Director": "Alan Taylor",
        "Genre": "Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYmMyNjEwM2YtYTY1OS00NmE4LWIxYjAtNjA5Y2MwNzg3MGRhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "6.3",
        "imdbID": "tt8110232",
        "Type": "movie"
    },
    {
        "Title": "Iron Man",
        "Year": "2008",
        "Rated": "PG-13",
        "Director": "Jon Favreau",
        "Genre": "Action, Adventure, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "7.9",
        "imdbID": "tt0371746",
        "Type": "movie"
    },
    {
        "Title": "Thor: Love and Thunder",
        "Year": "2022",
        "Rated": "PG-13",
        "Director": "Taika Waititi",
        "Genre": "Action, Adventure, Comedy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZjRiMDhiZjQtNjk5Yi00ZDcwLTkyYTEtMDc1NjdmNjFhNGIzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "6.1",
        "imdbID": "tt10648342",
        "Type": "movie"
    },
    {
        "Title": "Dune: Part One",
        "Year": "2021",
        "Rated": "PG-13",
        "Director": "Denis Villeneuve",
        "Genre": "Action, Adventure, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNWIyNmU5MGYtZDZmNi00ZjAwLWJlYjgtZTc0ZGIxMDE4ZGYwXkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg",
        "imdbRating": "8.0",
        "imdbID": "tt1160419",
        "Type": "movie"
    },
    {
        "Title": "Blade Runner 2049",
        "Year": "2017",
        "Rated": "R",
        "Director": "Denis Villeneuve",
        "Genre": "Action, Drama, Mystery",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.0",
        "imdbID": "tt1856101",
        "Type": "movie"
    },
    {
        "Title": "Arrival",
        "Year": "2016",
        "Rated": "PG-13",
        "Director": "Denis Villeneuve",
        "Genre": "Drama, Mystery, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_SX300.jpg",
        "imdbRating": "7.9",
        "imdbID": "tt2543164",
        "Type": "movie"
    },
    {
        "Title": "Her",
        "Year": "2014",
        "Rated": "R",
        "Director": "Spike Jonze",
        "Genre": "Drama, Romance, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.0",
        "imdbID": "tt1798709",
        "Type": "movie"
    },
    {
        "Title": "The Avengers",
        "Year": "2012",
        "Rated": "PG-13",
        "Director": "Joss Whedon",
        "Genre": "Action, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.0",
        "imdbID": "tt0848228",
        "Type": "movie"
    },
    {
        "Title": "Avatar",
        "Year": "2009",
        "Rated": "PG-13",
        "Director": "James Cameron",
        "Genre": "Action, Adventure, Fantasy",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMDEzMmQwZjctZWU2My00MWNlLWE0NjItMDJlYTRlNGJiZjcyXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "7.9",
        "imdbID": "tt0499549",
        "Type": "movie"
    },
    {
        "Title": "The Martian",
        "Year": "2015",
        "Rated": "PG-13",
        "Director": "Ridley Scott",
        "Genre": "Adventure, Drama, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_SX300.jpg",
        "imdbRating": "8.0",
        "imdbID": "tt3659388",
        "Type": "movie"
    },
    {
        "Title": "Jurassic Park",
        "Year": "1993",
        "Rated": "PG-13",
        "Director": "Steven Spielberg",
        "Genre": "Action, Adventure, Sci-Fi",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt0107290",
        "Type": "movie"
    },
    {
        "Title": "Top Gun: Maverick",
        "Year": "2022",
        "Rated": "PG-13",
        "Director": "Joseph Kosinski",
        "Genre": "Action, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMDBkZDNjMWEtOTdmMi00NmExLTg5MmMtNTFlYTJlNWY5YTdmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt1745960",
        "Type": "movie"
    },
    {
        "Title": "Batman Begins",
        "Year": "2005",
        "Rated": "PG-13",
        "Director": "Christopher Nolan",
        "Genre": "Action, Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMzA2NDQzZDEtNDU5Ni00YTlkLTg2OWEtYmQwM2Y1YTBjMjFjXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt0372784",
        "Type": "movie"
    },
    {
        "Title": "Kill Bill: Vol. 1",
        "Year": "2003",
        "Rated": "R",
        "Director": "Quentin Tarantino",
        "Genre": "Action, Crime, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZmMyYzJlZmYtY2I3NC00NjAyLTkyZWItZjdjZDI1YTYyYTEwXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt0266697",
        "Type": "movie"
    },
    {
        "Title": "Kill Bill: Vol. 2",
        "Year": "2004",
        "Rated": "R",
        "Director": "Quentin Tarantino",
        "Genre": "Action, Crime, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BY2FiNzhiZTctNzU1Mi00NDkwLWExNDMtZTg0MjYyNzhkNWNkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
        "imdbRating": "8.0",
        "imdbID": "tt0378194",
        "Type": "movie"
    },
    {
        "Title": "Snatch",
        "Year": "2001",
        "Rated": "R",
        "Director": "Guy Ritchie",
        "Genre": "Comedy, Crime",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYzk5NjJkMTQtN2IyNC00YWM5LTlhZmMtNGI3MWNhMTU1YTc4XkEyXkFqcGc@._V1_QL75_UY562_CR2,0,380,562_.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt0208092",
        "Type": "movie"
    },
    {
        "Title": "Lock, Stock and Two Smoking Barrels",
        "Year": "1998",
        "Rated": "R",
        "Director": "Guy Ritchie",
        "Genre": "Comedy, Crime",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMmY1M2M5ZmMtYzllZC00YzAxLTk4MjktZDJkNjA1MTUwMGQ4XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt0120735",
        "Type": "movie"
    },
    {
        "Title": "No Country for Old Men",
        "Year": "2007",
        "Rated": "R",
        "Director": "Ethan Coen, Joel Coen",
        "Genre": "Crime, Drama, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt0477348",
        "Type": "movie"
    },
    {
        "Title": "Fargo",
        "Year": "1996",
        "Rated": "R",
        "Director": "Joel Coen, Ethan Coen",
        "Genre": "Crime, Drama, Thriller",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNjg4MWE0MjEtODFhNy00MjA5LTg5ODktMzgwNWFmZTAwNjBlXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt0116282",
        "Type": "movie"
    },
    {
        "Title": "Prisoners",
        "Year": "2013",
        "Rated": "R",
        "Director": "Denis Villeneuve",
        "Genre": "Crime, Drama, Mystery",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTg0NTIzMjQ1NV5BMl5BanBnXkFtZTcwNDc3MzM5OQ@@._V1_SX300.jpg",
        "imdbRating": "8.2",
        "imdbID": "tt1392214",
        "Type": "movie"
    },
    {
        "Title": "Spotlight",
        "Year": "2015",
        "Rated": "R",
        "Director": "Tom McCarthy",
        "Genre": "Biography, Crime, Drama",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjIyOTM5OTIzNV5BMl5BanBnXkFtZTgwMDkzODE2NjE@._V1_SX300.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt1895587",
        "Type": "movie"
    },
    {
        "Title": "12 Years a Slave",
        "Year": "2013",
        "Rated": "R",
        "Director": "Steve McQueen",
        "Genre": "Biography, Drama, History",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1_QL75_UX380_CR0,1,380,562_.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt2024544",
        "Type": "movie"
    },
    {
        "Title": "Rush",
        "Year": "2013",
        "Rated": "R",
        "Director": "Ron Howard",
        "Genre": "Biography, Drama, Sport",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTZhOGQxM2ItNGQyYy00YzE5LWI5MjMtNmMzNGQzNDE1OTUzXkEyXkFqcGc@._V1_SX300.jpg",
        "imdbRating": "8.1",
        "imdbID": "tt1979320",
        "Type": "movie"
    }
];